### ISSUE TITLE
Paint 1 and Paint 2 for Body getting visually loaded with a Texture of 50

### ISSUE THREAD

**Issue by corsair99** [ManlyMarco/Illusion-Overlay-Mods#6] opened 2020-01-08 11:32 UTC
the Texture slider under Color, for body Paint 1 and Paint 2, is getting visually loaded as a default value of 50

it appears if you click Paint 1 or Paint 2 for body and/or adjust the slider it corrects visually

the value goes unchanged though so if you re-save it and load it again it behaves the same way

face Paint 1 and Paint 2 seem unaffected by this. persists in studioneo2

**Comment by ManlyMarco** [comment] 2020-01-11 17:19
Which game is this in, AIS? Can you make some screenshots or a video that shows how to reproduce the issue?

**Comment by corsair99** [comment] 2020-01-12 05:14
hmm after further investigating it seems as if Uncensor Selector is the culprit. if i remove Uncensor Selector the texture loads as normal

not sure if it's still up your alley but i have the screenshots to reproduce anyway, and my plugin log and game output log. 

reproduce guide
https://imgur.com/a/MMSe4rg

BepinEx log output
https://pastebin.com/7WTaz2Ex

ai game output_log
https://pastebin.com/CyRR9NZr

i updated to uncensorselector 3.9.1 from 3.9.0 and autotranslator to 4.8.1 to see if it helped after uploading my logs, and saw no change still.

**Comment by corsair99** [comment] 2020-01-27 15:22
just to drop an update it seems to be still broken on a vanilla install of STN's 3.1.1 repack

**Comment by ManlyMarco** [comment] 2020-02-23 13:59
Closing the issue since it's now posted in the uncensor selector repo, please comment on that one from now on.

**Closed by ManlyMarco** 2020-02-23 13:59 UTC
