### ISSUE TITLE
Suddenly cannot dump original texture for eye/iris overlay

### ISSUE THREAD

**Issue by hughorion** [ManlyMarco/Illusion-Overlay-Mods#24] opened 2023-03-01 17:42 UTC
Was working on a card and trying to export the native eye overlay as I could've sworn in the past there was a button to dump the in-game made iris, a prominent member in the Discord told be such a thing does exist but the button appears to be now absent from my updated BR KKS install.

I can still open the Material editor to manually export each part of the eye, but this is undesirable as the individual eye parts are uncolored and not the correct size when I try to put them all together in an image editor.

I have checked if my Overlay mod is updated, and it is indeed v6.1.1 so I'm at a bit of a loss. I really don't want to revert my BR version and risk breaking everything. I'll attach a link of an image I took showing my Eye Overlays section. It's important to note that there is no 'Dump Original Texture' button and the 'Export current texture' buttons don't do anything when pressed.
![image](https://user-images.githubusercontent.com/126706414/222219178-16bdf505-a4dc-4d80-b9b7-efefd1767aa6.png)

**Comment by ManlyMarco** [comment] 2023-03-01 22:07
Nothing related to exporting changed in a long time. I don't think you could have ever dumped body textures, it only works on clothes. Exporting only saves the currently loaded overlay.

**Comment by hughorion** [comment] 2023-03-01 22:58
Really? Maybe just an intense Mandela effect perhaps? I've searched on the Discord and many people have had the same question/issue, was exporting the entire iris as a texture a possibility a long time ago or am I just hysterical?

**Comment by ManlyMarco** [comment] 2023-03-02 07:26
The iris overlay feature didn't change since it was implemented pertty much, so I'm fairly sure it was never a thing.

**Comment by ManlyMarco** [comment] 2023-03-09 17:44
Since it seems like everything is working as intended, I'll close this issue. You might be able to dump the texture through MaterialEditor or RuntimeUnityEditor instead.

**Closed by ManlyMarco** 2023-03-09 17:44 UTC
